	DROP TABLE IF EXISTS {{DB_NAME}}.DBO.SUPERVISION_ALL_CASES
	DROP TABLE IF EXISTS {{DB_NAME}}.DBO.CasesToConvert
	DROP TABLE IF EXISTS {{DB_NAME}}.DBO.ChargesToConvert
	DROP TABLE IF EXISTS {{DB_NAME}}.DBO.PartiesToConvert
	DROP TABLE IF EXISTS {{DB_NAME}}.DBO.WarrantsToConvert
	DROP TABLE IF EXISTS {{DB_NAME}}.DBO.HearingsToConvert
	DROP TABLE IF EXISTS {{DB_NAME}}.DBO.EventsToConvert
GO
	SELECT DISTINCT
		  S.CaseID AS SUPERVISION_CASEID
		 ,CAHSUP.CaseNbr AS SUPERVISION_CASENUMBER
		 ,CAST(SUPCS.CaseUTypeID AS VARCHAR) + '-' + UC1.Code + ':' + UC1.[Description] AS SUPERVISION_CASETYPE
		 ,CAHCRT.CaseID AS COURTCASE_CASEID
		 ,CAHCRT.CaseNbr AS COURTCASE_CASENUMBER
		 ,CAST(CRTCS.CaseUTypeID AS VARCHAR) + '-' + UC2.Code + ':' + UC2.[Description] AS COURTCASE_CASETYPE
		 ,XCBC.CaseID AS SUPCASEID_XCASEBASECHRG
		 ,XCBC.ChargeID 
		 ,XCBC2.CaseID AS CLKCASEID_XCASEBASECHRG
		 ,'Supervision Case Linked to Court Case through ChargeID' AS TypeOfRow
	INTO {{DB_NAME}}.DBO.SUPERVISION_ALL_CASES
	FROM
		Justice.dbo.SupCaseHdr S WITH (NOLOCK)
			INNER JOIN Justice.DBO.CLKCASEHDR SUPCS WITH (NOLOCK) ON S.CaseID=SUPCS.CaseID
			INNER JOIN Justice.DBO.CaseAssignHist CAHSUP WITH (NOLOCK) ON SUPCS.CaseAssignmentHistoryIDCur=CAHSUP.CaseAssignmentHistoryID
			INNER JOIN Justice.DBO.UCODE UC1 WITH (NOLOCK) ON SUPCS.CaseUTypeID=UC1.CodeID
			INNER JOIN Justice.dbo.xCaseBaseChrg XCBC WITH (NOLOCK) ON S.CaseID=XCBC.CaseID
			INNER JOIN Justice.dbo.xCaseBaseChrg XCBC2 WITH (NOLOCK) ON XCBC.ChargeID=XCBC2.ChargeID AND S.CaseID<>XCBC2.CaseID
			LEFT JOIN Justice.dbo.SupCaseHdr SCH2 WITH (NOLOCK) ON XCBC2.CaseID=SCH2.CaseID
			INNER JOIN Justice.DBO.CLKCASEHDR CRTCS WITH (NOLOCK) ON XCBC2.CaseID=CRTCS.CaseID 
			INNER JOIN Justice.DBO.CaseAssignHist CAHCRT WITH (NOLOCK) ON CRTCS.CaseAssignmentHistoryIDCur=CAHCRT.CaseAssignmentHistoryID
			INNER JOIN Justice.DBO.UCODE UC2 WITH (NOLOCK) ON CRTCS.CaseUTypeID=UC2.CodeID
	WHERE
		SCH2.CaseID IS NULL
UNION
	SELECT DISTINCT
		  S.CaseID AS SUPERVISION_CASEID
		 ,CAHSUP.CaseNbr AS SUPERVISION_CASENUMBER
		 ,CAST(SUPCS.CaseUTypeID AS VARCHAR) + '-' + UC1.Code + ':' + UC1.[Description] AS SUPERVISION_CASETYPE
		 ,CAHCRT.CaseID AS COURTCASE_CASEID
		 ,CAHCRT.CaseNbr AS COURTCASE_CASENUMBER
		 ,CAST(CRTCS.CaseUTypeID AS VARCHAR) + '-' + UC2.Code + ':' + UC2.[Description] AS COURTCASE_CASETYPE
		 ,XCBC.CaseID AS SUPCASEID_XCASEBASECHRG
		 ,XCBC.ChargeID 
		 ,XCBC2.CaseID AS CLKCASEID_XCASEBASECHRG
		,'Supervision Case Linked to another Supervision Case through ChargeID' AS TypeOfRow
	FROM
		Justice.dbo.SupCaseHdr S WITH (NOLOCK)
			INNER JOIN Justice.DBO.CLKCASEHDR SUPCS WITH (NOLOCK) ON S.CaseID=SUPCS.CaseID
			INNER JOIN Justice.DBO.CaseAssignHist CAHSUP WITH (NOLOCK) ON SUPCS.CaseAssignmentHistoryIDCur=CAHSUP.CaseAssignmentHistoryID
			INNER JOIN Justice.DBO.UCODE UC1 WITH (NOLOCK) ON SUPCS.CaseUTypeID=UC1.CodeID
			INNER JOIN Justice.dbo.xCaseBaseChrg XCBC WITH (NOLOCK) ON S.CaseID=XCBC.CaseID
			INNER JOIN Justice.dbo.xCaseBaseChrg XCBC2 WITH (NOLOCK) ON XCBC.ChargeID=XCBC2.ChargeID AND S.CaseID<>XCBC2.CaseID
			INNER JOIN Justice.dbo.SupCaseHdr SCH2 WITH (NOLOCK) ON XCBC2.CaseID=SCH2.CaseID
			INNER JOIN Justice.DBO.CLKCASEHDR CRTCS WITH (NOLOCK) ON SCH2.CaseID=CRTCS.CaseID 
			INNER JOIN Justice.DBO.CaseAssignHist CAHCRT WITH (NOLOCK) ON CRTCS.CaseAssignmentHistoryIDCur=CAHCRT.CaseAssignmentHistoryID
			INNER JOIN Justice.DBO.UCODE UC2 WITH (NOLOCK) ON CRTCS.CaseUTypeID=UC2.CodeID
UNION
	SELECT DISTINCT
		  S.CaseID AS SUPERVISION_CASEID
		 ,CAHSUP.CaseNbr AS SUPERVISION_CASENUMBER
		 ,CAST(SUPCS.CaseUTypeID AS VARCHAR) + '-' + UC1.Code + ':' + UC1.[Description] AS SUPERVISION_CASETYPE
		 ,NULL AS COURTCASE_CASEID
		 ,NULL AS COURTCASE_CASENUMBER
		 ,NULL AS COURTCASE_CASETYPE
		 ,XCBC.CaseID AS SUPCASEID_XCASEBASECHRG
		 ,XCBC.ChargeID 
		 ,NULL AS CLKCASEID_XCASEBASECHRG
		,'Supervision Case Not Linked to any another Case.' AS TypeOfRow
	FROM
		Justice.dbo.SupCaseHdr S WITH (NOLOCK)
			INNER JOIN Justice.DBO.CLKCASEHDR SUPCS WITH (NOLOCK) ON S.CaseID=SUPCS.CaseID
			INNER JOIN Justice.DBO.CaseAssignHist CAHSUP WITH (NOLOCK) ON SUPCS.CaseAssignmentHistoryIDCur=CAHSUP.CaseAssignmentHistoryID
			INNER JOIN Justice.DBO.UCODE UC1 WITH (NOLOCK) ON SUPCS.CaseUTypeID=UC1.CodeID
			INNER JOIN Justice.dbo.xCaseBaseChrg XCBC WITH (NOLOCK) ON S.CaseID=XCBC.CaseID
			LEFT JOIN Justice.dbo.xCaseBaseChrg XCBC2 WITH (NOLOCK) ON XCBC.ChargeID=XCBC2.ChargeID AND S.CaseID<>XCBC2.CaseID
	WHERE
		XCBC2.CaseID IS NULL
GO
	SELECT
		 S.SUPERVISION_CASEID AS CaseID
		,'SUPCASEHDR' AS TypeOfCase
	INTO {{DB_NAME}}.DBO.CasesToConvert
	FROM
		{{DB_NAME}}.DBO.SUPERVISION_ALL_CASES S
	WHERE
		S.TYPEOFROW='Supervision Case Not Linked to any another Case.'
	GROUP BY 
		S.SUPERVISION_CASEID
UNION
	SELECT
		 S.SUPERVISION_CASEID AS CaseID
		,'SUPCASEHDR' AS TypeOfCase
	FROM
		{{DB_NAME}}.DBO.SUPERVISION_ALL_CASES S
	WHERE
		S.TYPEOFROW='Supervision Case Linked to another Supervision Case through ChargeID'
	GROUP BY 
		S.SUPERVISION_CASEID
UNION
	SELECT
		 S.SUPERVISION_CASEID AS CaseID
		,'SUPCASEHDR' AS TypeOfCase
	FROM
		{{DB_NAME}}.DBO.SUPERVISION_ALL_CASES S
	WHERE
		S.TYPEOFROW='Supervision Case Linked to Court Case through ChargeID'
	GROUP BY 
		S.SUPERVISION_CASEID
UNION
	SELECT
		 S.COURTCASE_CASEID AS CaseID
		,'CLKCASEHDR' AS TypeOfCase
	FROM
		{{DB_NAME}}.DBO.SUPERVISION_ALL_CASES S
	WHERE
		S.TYPEOFROW='Supervision Case Linked to Court Case through ChargeID'
	GROUP BY 
		S.COURTCASE_CASEID
GO
	ALTER TABLE {{DB_NAME}}.DBO.CasesToConvert ALTER COLUMN CaseID INT NOT NULL
GO
	ALTER TABLE {{DB_NAME}}.DBO.CasesToConvert ADD CONSTRAINT PK_CaseID PRIMARY KEY (CaseID)
GO
